
name = input("escribe tu nombre  ")
age = input("escribe tu edad  ")
veces = int(input("escribe un numero del 1 al 10 "))
nage = int (age)
print("tu nombre es  " + name)
print("tu edad es  "+ age)
new_age= str(nage + 25)
message = (" tendrá " + new_age + " en el 2045 " )
print(veces * message)
